draw = {
    "Spain": "Matt",
    "Colombia": "Matt",
    "Austria": "Matt",
    "Canada": "Matt",
    "Saudi Arabia": "Matt",
    "South Africa": "Matt",
    "France": "Dan",
    "Uruguay": "Dan",
    "Japan": "Dan",
    "Sweden": "Dan",
    "Paraguay": "Dan",
    "Iran": "Dan",
    "England": "Rhys",
    "Belgium": "Rhys",
    "Morocco": "Rhys",
    "Ivory Coast": "Rhys",
    "Ghana": "Rhys",
    "Czechia": "Rhys",
    "Brazil": "Daf",
    "USA": "Daf",
    "Scotland": "Daf",
    "Australia": "Daf",
    "New Zealand": "Daf",
    "Egypt": "Daf",
    "Argentina": "Llyr",
    "Switzerland": "Llyr",
    "Mexico": "Llyr",
    "Ecuador": "Llyr",
    "Algeria": "Llyr",
    "Tunisia": "Llyr",
    "Portugal": "Joey",
    "Netherlands": "Joey",
    "Norway": "Joey",
    "Bosnia-Herzegovina": "Joey",
    "Iraq": "Joey",
    "South Korea": "Joey",
    "Germany": "Jac",
    "Croatia": "Jac",
    "Senegal": "Jac",
    "Turkiye": "Jac",
    "Congo DR": "Jac",
    "Qatar": "Jac",
    "Cape Verde": "Neb",
    "Curaçao": "Neb",
    "Haiti": "Neb",
    "Jordan": "Neb",
    "Panama": "Neb",
    "Uzbekistan": "Neb",
}
